### ISSUE TITLE
File Encryption Enhancement

### ISSUE THREAD

**Issue by shravan097** [shravan097/Mero-Home-Cloud#13]
Let the user select encryption option. If selected "Yes" then let user set password for the file and encrypt it.

**Comment by shravan097** [comment]
Updated Upload With Password functions.  Now needs to prompt password request for Downloading file if Password exists.

**Comment by riteishB** [comment]
I uploaded a doc with password. Then Downloaded the document. Didn't get any prompt to provide the password

**Comment by shravan097** [comment]
Yes. I still need to work on that.  I thought of using JS to alert the user using "alert()" that prompts user to enter password and then check if hash of user input is same as password hash.  Felt asleep early last night lol. :) Will implement that soon.

**Comment by shravan097** [comment]
Password Input works properly now.  Further improvement such as attempt of tries can be made.
