### ISSUE TITLE
Delete Issue

### ISSUE THREAD

**Issue by shravan097** [shravan097/Mero-Home-Cloud#6]
Delete button is missing.  When using Delete button from SQL Admin page, the delete **does not ** delete the original file from the folder.  Needs a script that does this every time the file gets deleted from database.

**Comment by shravan097** [comment]
Delete is not deleting the entire folder of date, only files are being deleted of relative path.

**Comment by riteishB** [comment]
have to add a logic, which will, after deleting the file, check if the folder is empty. If it is empty, it will delete the folder, if not it will leave it as it is.

**Comment by riteishB** [comment]
Updated view.html so that the delete button appears for view tab. Added the delete button for search bar functionality too.
